language: python

env:
  global:
    - PYTHON3.7=3.7.2
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: sh
      env: PYTHON_VERSION
      before_install: 
        - bash scripts/osx.sh

  
install:
  - python --version
  - python setup.py install
  
script: 
  - python setup.py test
